### ISSUE TITLE
[fix] Bug in figure for regularized logistic regression

### ISSUE THREAD

**Issue by giuseppec** [slds-lmu/lecture_sl#222]
On slide 4 in [regu-enetlogreg](https://github.com/slds-lmu/lecture_sl/blob/main/slides-pdf/slides-regu-enetlogreg.pdf) we say "fit looks pretty good" for lambda = 1, but the figure looks like a bad fit as the prediction surface only shows that one class (the violet one) is predicted. Also, the original class labels seem flipped compared to the other two figures.

Here how it currently looks like:
![image](https://github.com/user-attachments/assets/6974c3bd-cc82-4d6a-93c4-25eb80358d00)

**Comment by chriskolb** [comment]
fixed
